import React from 'react';
import PropTypes, { string } from 'prop-types';
import { CommandBarButton as CommandBarButtonOF, IContextualMenuProps } from '@fluentui/react';
import pickWithValues from "usr/a_lib/utils/pickWithValues";
import { MenuItem, MenuItemProps } from "usr/atoms/buttons/MenuItem.props"

export interface CommandBarButtonProps {
    ariaLabel?: string;
    ariaDescription?: string;
    ariaHidden?: boolean;
    toggle?: boolean;
    href?: string;
    disabled?: boolean;
    allowDisabledFocus?: boolean;
    text: string;
    onClick?: () => void;

    //for menu
    menuProps: MenuItemProps[];
}



/**
 * Button is generated by Webcodesk. Replace this comment with a valuable description.
 */
class CommandBarButton extends React.Component<CommandBarButtonProps, any> {

    static propTypes: PropTypes.InferProps<CommandBarButtonProps> = {

        /**
         * Props for button menu. Providing this will default to showing the menu icon. See menuIconProps for overriding
         * how the default icon looks. Providing this in addition of onClick and setting the split property to true will
         * render a SplitButton.
         */
        menuProps: PropTypes.arrayOf(PropTypes.shape(MenuItem)),
        /**
        * The aria label of the button for the benefit of screen readers.
        */
        ariaLabel: PropTypes.string,
        /**
         * Detailed description of the button for the benefit of screen readers.
         *
         * Besides the compound button, other button types will need more information provided to screen reader.
         */
        ariaDescription: PropTypes.string,
        /**
         * If provided and is true it adds an 'aria-hidden' attribute instructing screen readers to ignore the element.
         */
        ariaHidden: PropTypes.bool,
        /**
         * Whether button is a toggle button with distinct on and off states. This should be true for buttons that permanently
         * change state when a press event finishes, such as a volume mute button.
         */
        toggle: PropTypes.bool,
        /**
         * If provided, this component will be rendered as an anchor.
         * @defaultvalue ElementType.anchor
         */
        href: PropTypes.string,
        /**
         * Whether the button is disabled
         */
        disabled: PropTypes.bool,
        /**
       * Whether the button can have focus in disabled mode
       */
        allowDisabledFocus: PropTypes.bool,
        /**
         * Label of the button.
         */
        text: PropTypes.string.isRequired,
        /**
         * Triggered when the user clicks on the button
         */
        onClick: PropTypes.func,
    };

    static defaultProps: CommandBarButtonProps = {
        text: 'Button',
        menuProps: [],
    };

    // constructor(props: PrimaryButtonProps) {
    //   super(props);
    // }

    handleButtonClick = (e: React.MouseEvent<HTMLElement>): void => {
        if (e) {
            e.stopPropagation();
            e.preventDefault();
        }
        if (this.props.onClick) {
            this.props.onClick();
        }
    };

    render() {

        const {
            ariaLabel,
            ariaDescription,
            ariaHidden,
            toggle,
            href,
            disabled,
            allowDisabledFocus,
            text,
            menuProps,
        } = this.props;
        //const menuProps: IContextualMenuProps = {
        //    items: [
        //        {
        //            key: 'emailMessage',
        //            text: 'Email message',
        //            iconProps: { iconName: 'Mail' },
        //        },
        //        {
        //            key: 'calendarEvent',
        //            text: 'Calendar event',
        //            iconProps: { iconName: 'Calendar' },
        //        },
        //    ],
        //};
        const properties = pickWithValues({ ariaLabel, ariaDescription, ariaHidden, toggle, href, disabled, allowDisabledFocus, text, menuProps });
        
        return (    
            <CommandBarButtonOF
                {...properties}
                onClick={this.handleButtonClick}
            />);
    }
}

export default CommandBarButton;
